name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sunstone:
    name: EJX Test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.2
          - 3.3
          - 3.4
          - 3.5.0-preview1

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test